# LLVM configuration settings for SML/NJ
#
# COPYRIGHT (c) 2025 The Fellowship of SML/NJ (https://www.smlnj.org)
# All rights reserved.
#
# This file is included before the LLVM sources are configured.  It enables
# the LLVM features that SML/NJ requires and disables the components that
# we do not use.  The former are set unconditionally, while the latter are
# defaults that can be overridden on the command line.
#

# Required by the code generator
#
set(LLVM_ENABLE_DUMP ON)

# Defaults for the components that we do not use
#
set(_smlnj_llvm_unused
  LLVM_ENABLE_BINDINGS
  LLVM_ENABLE_LIBXML2
  LLVM_ENABLE_OCAMLDOC
  LLVM_ENABLE_ZSTD
  LLVM_INCLUDE_BENCHMARKS
  LLVM_INCLUDE_DOCS
  LLVM_INCLUDE_EXAMPLES
  LLVM_INCLUDE_TESTS
  LLVM_INCLUDE_UTILS
  LLVM_TOOL_BUGPOINT_BUILD
  LLVM_TOOL_BUGPOINT_PASSES_BUILD
  LLVM_TOOL_DSYMUTIL_BUILD
  LLVM_TOOL_GOLD_BUILD
  LLVM_TOOL_LLI_BUILD
  LLVM_TOOL_LLVM_AR_BUILD
  LLVM_TOOL_LLVM_AS_BUILD
  LLVM_TOOL_LLVM_AS_FUZZER_BUILD
  LLVM_TOOL_LLVM_BCANALYZER_BUILD
  LLVM_TOOL_LLVM_CAT_BUILD
  LLVM_TOOL_LLVM_CFI_VERIFY_BUILD
  LLVM_TOOL_LLVM_CGDATA_BUILD
  LLVM_TOOL_LLVM_COV_BUILD
  LLVM_TOOL_LLVM_CTXPROF_UTIL_BUILD
  LLVM_TOOL_LLVM_CVTRES_BUILD
  LLVM_TOOL_LLVM_CXXDUMP_BUILD
  LLVM_TOOL_LLVM_CXXFILT_BUILD
  LLVM_TOOL_LLVM_CXXMAP_BUILD
  LLVM_TOOL_LLVM_C_TEST_BUILD
  LLVM_TOOL_LLVM_DEBUGINFO_ANALYZER_BUILD
  LLVM_TOOL_LLVM_DEBUGINFOD_BUILD
  LLVM_TOOL_LLVM_DEBUGINFOD_FIND_BUILD
  LLVM_TOOL_LLVM_DIFF_BUILD
  LLVM_TOOL_LLVM_DIS_BUILD
  LLVM_TOOL_LLVM_DWARFDUMP_BUILD
  LLVM_TOOL_LLVM_DWARFUTIL_BUILD
  LLVM_TOOL_LLVM_DWP_BUILD
  LLVM_TOOL_LLVM_EXEGESIS_BUILD
  LLVM_TOOL_LLVM_EXTRACT_BUILD
  LLVM_TOOL_LLVM_GSYMUTIL_BUILD
  LLVM_TOOL_LLVM_IFS_BUILD
  LLVM_TOOL_LLVM_ISEL_FUZZER_BUILD
  LLVM_TOOL_LLVM_ITANIUM_DEMANGLE_FUZZER_BUILD
  LLVM_TOOL_LLVM_JITLINK_BUILD
  LLVM_TOOL_LLVM_JITLISTENER_BUILD
  LLVM_TOOL_LLVM_LINK_BUILD
  LLVM_TOOL_LLVM_LIPO_BUILD
  LLVM_TOOL_LLVM_LTO2_BUILD
  LLVM_TOOL_LLVM_LTO_BUILD
  LLVM_TOOL_LLVM_MCA_BUILD
  LLVM_TOOL_LLVM_MC_ASSEMBLE_FUZZER_BUILD
  LLVM_TOOL_LLVM_MC_BUILD
  LLVM_TOOL_LLVM_MC_DISASSEMBLE_FUZZER_BUILD
  LLVM_TOOL_LLVM_MICROSOFT_DEMANGLE_FUZZER_BUILD
  LLVM_TOOL_LLVM_ML_BUILD
  LLVM_TOOL_LLVM_MODEXTRACT_BUILD
  LLVM_TOOL_LLVM_MT_BUILD
  LLVM_TOOL_LLVM_NM_BUILD
  LLVM_TOOL_LLVM_OBJCOPY_BUILD
  LLVM_TOOL_LLVM_OBJDUMP_BUILD
  LLVM_TOOL_LLVM_OPT_FUZZER_BUILD
  LLVM_TOOL_LLVM_OPT_REPORT_BUILD
  LLVM_TOOL_LLVM_PDBUTIL_BUILD
  LLVM_TOOL_LLVM_PROFDATA_BUILD
  LLVM_TOOL_LLVM_PROFGEN_BUILD
  LLVM_TOOL_LLVM_RC_BUILD
  LLVM_TOOL_LLVM_READOBJ_BUILD
  LLVM_TOOL_LLVM_READTAPI_BUILD
  LLVM_TOOL_LLVM_REDUCE_BUILD
  LLVM_TOOL_LLVM_REMARKUTIL_BUILD
  LLVM_TOOL_LLVM_RTDYLD_BUILD
  LLVM_TOOL_LLVM_SHLIB_BUILD
  LLVM_TOOL_LLVM_SIM_BUILD
  LLVM_TOOL_LLVM_SIZE_BUILD
  LLVM_TOOL_LLVM_SPECIAL_CASE_LIST_FUZZER_BUILD
  LLVM_TOOL_LLVM_SPLIT_BUILD
  LLVM_TOOL_LLVM_STRESS_BUILD
  LLVM_TOOL_LLVM_STRINGS_BUILD
  LLVM_TOOL_LLVM_SYMBOLIZER_BUILD
  LLVM_TOOL_LLVM_TLI_CHECKER_BUILD
  LLVM_TOOL_LLVM_UNDNAME_BUILD
  LLVM_TOOL_LLVM_XRAY_BUILD
  LLVM_TOOL_LTO_BUILD
  LLVM_TOOL_OBJ2YAML_BUILD
  LLVM_TOOL_OPT_BUILD
  LLVM_TOOL_OPT_VIEWER_BUILD
  LLVM_TOOL_REMARKS_SHLIB_BUILD
  LLVM_TOOL_REDUCE_CHUNK_LIST_BUILD
  LLVM_TOOL_SANCOV_BUILD
  LLVM_TOOL_SANSTATS_BUILD
  LLVM_TOOL_VERIFY_USELISTORDER_BUILD
  LLVM_TOOL_VFABI_DEMANGLE_FUZZER_BUILD)

foreach(_var IN LISTS _smlnj_llvm_unused)
  set(${_var} OFF CACHE BOOL "LLVM component that is not used by SML/NJ")
  mark_as_advanced(${_var})
endforeach()
unset(_smlnj_llvm_unused)
unset(_var)
